### ISSUE TITLE
GoTo Reference Not Working

### ISSUE THREAD

**Issue by zero-radiance** [MattSutherlin/HLSL_ST3#6]
Hi Matt,

Nice work on the extension.
It works great, except that I can't get the list of references to show up when I press Shift+F12.
Possibly related, there's no function call highlighting.

There's a similar extension which I am currently using which doesn't suffer from these two issues:
https://github.com/jocopa3/sublime-shaders

Unfortunately, it has other problems...

Perhaps you may have an idea how to fix this?

Thanks!

**Comment by MattSutherlin** [comment]
Hey,

On the function call highlighting issue, that's likely because I scope calls separate from definitions.  I did that so calls resolve to definitions for GoTo Definition and never the other way around.  My custom ST3 Theme ([Rock Lobster](https://github.com/MattSutherlin/RockLobster_ST3Theme)) solves the issue by specifically knowing about the distinction.  I mention that because maybe you want to use it, but that's obviously not a real solution to the overall problem.

On the GoTo Reference issue, I didn't even realize that was a thing.  I have a feeling that it's probably also related to my choice to scope function calls separately, but the ST3 documentation doesn't really explicitly go into how various syntax scopes feed into these systems so there's a lot of guessing and trial and error involved.

Either way, I'll take a look and see if I can't figure out what's going on and get a solution that addresses your stuff while maintaining what I was intending.  Fingers crossed!

**Comment by zero-radiance** [comment]
Thanks, Matt!

Sorry I can't help you more. I tried fiddling around with the existing code, but since I don't have the big picture of how Sublime extensions work, I didn't really get far.

**Comment by MattSutherlin** [comment]
Hey!

First, sorry it took so long to get to this.

That said, I think I figured it out and the Test branch has that potential fix.  If you can grab and verify Test, that'd help speed things up for me.  Otherwise I'll tinker for a few days until I'm confident I haven't broken anything in the process and then merge to master and make a new release on PackageControl.

**Comment by zero-radiance** [comment]
Hi Matt,

That’s great news! I’d love to test it... but I’m on vacation. :-)

I will definitely check it out when I get back.

**Comment by zero-radiance** [comment]
Hi Matt,

Just gave your test branch a go - everything seems to work as expected. Great job!

On Sat, Jan 5, 2019 at 6:01 AM Evgenii Golubev <evgenii.golubev@outlook.com<mailto:evgenii.golubev@outlook.com>> wrote:
Hi Matt,

That’s great news! I’d love to test it... but I’m on vacation. :-)

I will definitely check it out when I get back.

Thanks!


________________________________

**Comment by MattSutherlin** [comment]
Awesome, glad that worked out.  I've been busier than expected recently, but I'll find some time this week to pull it to master and issue a release to PackageControl.

Thanks for filing the issue and verifying the fix!
